### ISSUE TITLE
Invalid literal for int() with base 10: '26.5'

### ISSUE THREAD

**Issue by ZalewskiPiotr** [ZalewskiPiotr/jira_reader#30]
Traceback (most recent call last):
  File "cli.py", line 4, in <module>
  File "runner.py", line 145, in main
  File "jira_reader\jira_reader.py", line 102, in show_main_epic_data
  File "jira_reader\jira.py", line 237, in get_information_about_epic
  File "jira_reader\jira.py", line 215, in get_epic_budget
ValueError: invalid literal for int() with base 10: '26.5'
[10288] Failed to execute script 'cli' due to unhandled exception!

**Comment by ZalewskiPiotr** [comment]
W sumie to nie wiem nawet na jakim epiku się wywaliło. Przydałby się jakiś bardziej pomocny komunikat lub może logowanie informacji do pliku
